/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package educacion;

import org.apache.jena.query.*;
import org.apache.jena.rdf.model.RDFNode;
import javax.swing.table.DefaultTableModel;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.ButtonModel;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class BuscadorEducacion extends javax.swing.JFrame {

    String servicio = "http://localhost:8890/sparql";
    String grafo = "http://localhost:8890/SBCEducation";

    public BuscadorEducacion() {
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void initComponents() {

        JPanel panel = new javax.swing.JPanel();
    	jPanel1 = new javax.swing.JPanel();                        
        texto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        area1 = new javax.swing.JTextArea();
        JButton jButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                        
        
        jScrollPane1.setViewportView(area1);
        jButton.setText("BUSCAR");
        
        jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLay = new javax.swing.GroupLayout(jPanel1);
        
        jPanel1.setLayout(panelLay);
        
        panelLay.setHorizontalGroup(
        		panelLay.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLay.createSequentialGroup()
                .addGap(76, 76, 76)                                                
                .addGroup(panelLay.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLay.createSequentialGroup()                        
                        .addComponent(texto, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE))
                    .addGroup(panelLay.createSequentialGroup()                        
                        .addComponent(jButton)
                        .addGap(69, 69, 69)))                
                .addGap(143, 143, 143))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLay.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );
        panelLay.setVerticalGroup(
        		panelLay.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLay.createSequentialGroup()
                .addGroup(panelLay.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)                    
                    .addGroup(panelLay.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panelLay.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)                            
                            .addComponent(texto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))                        
                        .addComponent(jButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }
    
    //Accion del Boton
    private void jButtonActionPerformed(java.awt.event.ActionEvent evt) {
        String ritem2 = texto.getText().toString();
    	
        System.out.println("Buscando la siguiente consulta:\n" + ritem2);
        if (texto.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Llenar los campos");
        } else {
            if (ritem2.equals(ritem2)) {
                consulta();
            }
        }

    }
    
    //Metodo de la cosulta
    public void consulta() {
    	//Aqui se realizamo la consulta
        String ver = "";
        ver = String.valueOf(texto.getText());

        area1.setText(" ");
        area1.append("Resultado de la busqueda\n");

        String sentencia = "PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>"
                + "PREFIX dbo: <http://dbpedia.org/ontology/>"
                + "SELECT DISTINCT ?o  "
                + "WHERE {"
                + "?s ?p ?o "
                + "FILTER regex(?o, '" + ver + "','i')}";

        pregunta(sentencia);

    }
    
    //Método Para visualizar la consulta
    public void pregunta(String sentencia) {
    	
        //Recibo las conexiones tanto para el servicio la sentencia y el grafo
    	//al cual voy hacer la consulta
        QueryExecution qexec1 = QueryExecutionFactory.sparqlService(servicio, sentencia, grafo);
        ResultSet results = qexec1.execSelect();

        while (results.hasNext()) {
            QuerySolution sol = results.nextSolution();
            RDFNode o = sol.get("S");
            RDFNode s = sol.get("o");            
            area1.append("\n");
            area1.append(s.toString() + "\n");

        }
        System.out.close();

    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscadorEducacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscadorEducacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscadorEducacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscadorEducacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscadorEducacion().setVisible(true);
            }
        });
    }
    
    private javax.swing.JTextArea area1;
    private javax.swing.JButton jButton;    
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;    
    private javax.swing.JTextField texto;
    
}
